### ISSUE TITLE
[chore] 프론트 개발환경 세팅 

### ISSUE THREAD

**Issue by suhyeon3484** [tukcom2023CD/RISING#9]
## 💡 구현할 기능 설명
프론트 개발을 위한 prettier, eslint, tailwind, typescipt 설정 및 페이지 생성

## ❗체크리스트
- [x] 모든 포지션의 팀원들이 이해할 수 있도록 충분한 설명을 제공하나요?
- [x] 제목 형식을 지키고 브랜치 및 라벨을 할당했나요?

**Comment by KoneJ** [comment]
좋아용
